#!/bin/bash

set +e

while [ -f "/data/timelapse/control/NO_SHUTDOWN" ]
do
	sleep 5s
done

timelapse-reset-wakeup
sudo systemctl enable timelapse.service

timelapse-set-led blink 0 0 0

sudo shutdown now 
